# Example hyprlax TOML configuration (scaffold)
#
# Default values optimized for 10 workspaces without edge smearing:
# - shift_percent = 1.5% of screen width per workspace
# - Works consistently across all screen sizes (1080p, 1440p, 4K, ultrawide)
# - layer scale = 1.3x (30% larger than viewport)
# - Provides 15% margin each side to prevent edge artifacts
#
[global]
fps = 144
duration = 1.0
shift_percent = 1.5   # 1.5% of screen width per workspace (resolution-independent)
# shift = 1.5         # Alternative: legacy syntax also works (values ≤10 are percentages)
easing = "expo"
debug = false
vsync = false
idle_poll_rate = 2.0

[[global.layers]]
path = "images/bg.png"
shift_multiplier = 0.25
scale = 1.3  # 30% larger to accommodate parallax shift without edge artifacts
opacity = 1.0
blur = 0.0

[[global.layers]]
path = "images/fg.png"
shift_multiplier = 0.75  # Foreground moves more for depth effect
scale = 1.3  # Match background scale for consistency
opacity = 0.9
blur = 0.0

# Forward-compatible sections for Issue #28
# [monitors.overrides."DP-1"]
#   # override globals or layers here
#
# [monitors.configs."HDMI-*"]
# clear_layers = true
# [[monitors.configs."HDMI-*".layers]]
# path = "images/ultrawide_bg.png"
# shift_multiplier = 0.2
# opacity = 1.0