# Example hyprlax TOML configuration (scaffold)

[global]
fps = 144
duration = 1.0
shift = 200
easing = "expo"
debug = false
vsync = false
idle_poll_rate = 2.0

[[global.layers]]
path = "images/bg.png"
shift_multiplier = 0.25
opacity = 1.0
blur = 0.0

[[global.layers]]
path = "images/fg.png"
shift_multiplier = 1.0
opacity = 0.9
blur = 0.0

# Forward-compatible sections for Issue #28
# [monitors.overrides."DP-1"]
#   # override globals or layers here
#
# [monitors.configs."HDMI-*"]
# clear_layers = true
# [[monitors.configs."HDMI-*".layers]]
# path = "images/ultrawide_bg.png"
# shift_multiplier = 0.2
# opacity = 1.0
