name: Deploy Website

on:
  push:
    branches:
      - master
    paths:
      - 'website/**'
      - 'install-remote.sh'
      - '.github/workflows/deploy-website.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BUNNY_PUBLIC_BASE_URL: https://hyprlax.com
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: website
      run: |
        rm -f pnpm-lock.yaml
        pnpm install

    - name: Build website
      working-directory: website
      run: pnpm build

    - name: Deploy to Bunny CDN
      uses: R-J-dev/bunny-deploy@v2.0.3
      with:
        access-key: ${{ secrets.BUNNY_API_KEY }}
        directory-to-upload: "./website/dist"
        storage-endpoint: "https://storage.bunnycdn.com"
        storage-zone-name: ${{ secrets.BUNNY_STORAGE_ZONE }}
        storage-zone-password: ${{ secrets.BUNNY_STORAGE_PASSWORD }}
        concurrency: "50"
        enable-delete-action: true
        enable-purge-pull-zone: false
        replication-timeout: "15000"

    - name: Purge Bunny CDN URLs (root)
      if: ${{ success() && secrets.BUNNY_API_KEY }}
      env:
        BUNNY_API_KEY: ${{ secrets.BUNNY_API_KEY }}
      run: |
        set -euo pipefail
        echo "Purging URLs under ${BUNNY_PUBLIC_BASE_URL}"
        # Purge files from build output
        mapfile -d '' FILES < <(find website/dist -type f -print0)
        for file in "${FILES[@]}"; do
          rel="${file#website/dist/}"
          url="${BUNNY_PUBLIC_BASE_URL%/}/${rel}"
          echo "PURGE $url"
          curl -sS -X POST -H "AccessKey: ${BUNNY_API_KEY}" -G \
            --data-urlencode "url=$url" \
            "https://api.bunny.net/purge" || true
        done
        # Also purge base index and 404 explicitly
        curl -sS -X POST -H "AccessKey: ${BUNNY_API_KEY}" -G \
          --data-urlencode "url=${BUNNY_PUBLIC_BASE_URL%/}/" \
          "https://api.bunny.net/purge" || true
        curl -sS -X POST -H "AccessKey: ${BUNNY_API_KEY}" -G \
          --data-urlencode "url=${BUNNY_PUBLIC_BASE_URL%/}/404.html" \
          "https://api.bunny.net/purge" || true
