name: Release

on:
  push:
    tags:
      # Only match stable version tags (no dash)
      # v1.0.0, v2.1.3 etc. (NOT v1.0.0-beta.1)
      - 'v[0-9]+.[0-9]+.[0-9]+' 

permissions:
  contents: write

jobs:
  validate-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Validate tag is from master
        run: |
          # Get the branch containing this tag
          BRANCH=$(git branch -r --contains ${{ github.ref_name }} | grep -v HEAD | head -1 | sed 's/.*origin\///')
          echo "Stable release tag ${{ github.ref_name }} is on branch: $BRANCH"
          
          # Stable releases must be from master branch
          if [[ "$BRANCH" != "master" ]] && [[ "$BRANCH" != "main" ]]; then
            echo "::error::Stable release tags must be created from master/main branch!"
            echo "Current branch is: $BRANCH"
            echo "For pre-releases from feature branches, use version tags like v1.0.0-beta.1"
            exit 1
          fi
          
          echo "✅ Stable release tag is correctly on master/main branch"

  build:
    needs: validate-branch
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            cc: gcc

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwayland-dev \
          wayland-protocols \
          libegl1-mesa-dev \
          libgles2-mesa-dev \
          pkg-config \
          make

    - name: Write VERSION file from tag
      run: |
        # Extract version from tag (remove 'v' prefix)
        VERSION="${GITHUB_REF_NAME#v}"
        echo "$VERSION" > VERSION
        echo "Building version: $VERSION"

    - name: Build
      env:
        CC: ${{ matrix.cc }}
      run: |
        make clean
        make
        
    - name: Create binary names
      id: binary
      run: |
        echo "hyprlax_name=hyprlax-${{ matrix.arch }}" >> $GITHUB_OUTPUT

    - name: Rename binary
      run: |
        mv hyprlax ${{ steps.binary.outputs.hyprlax_name }}
        chmod +x ${{ steps.binary.outputs.hyprlax_name }}

    - name: Upload hyprlax artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.binary.outputs.hyprlax_name }}
        path: ${{ steps.binary.outputs.hyprlax_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./binaries

    - name: Prepare release files
      run: |
        # Move all binaries to root
        find ./binaries -type f -name 'hyprlax-*' -exec mv {} . \;
        
        # Check if we have the x86_64 binary
        if [ ! -f hyprlax-x86_64 ]; then
          echo "Error: hyprlax-x86_64 binary not found!"
          exit 1
        fi
        
        # Create checksums
        sha256sum hyprlax-* > SHA256SUMS
        
        # List files for verification
        ls -la hyprlax-* SHA256SUMS

    - name: Extract version from tag
      id: version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Generate release notes
      id: notes
      run: |
        # Get commits since last tag
        PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        if [ -z "$PREV_TAG" ]; then
          echo "notes=Initial release of hyprlax" >> $GITHUB_OUTPUT
        else
          NOTES=$(git log ${PREV_TAG}..HEAD --pretty=format:"- %s" | head -20)
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.version }}
        name: ${{ steps.version.outputs.version }}
        body: |
          ## Release ${{ steps.version.outputs.version }}
          
          Multi-compositor parallax wallpaper engine for Linux.
          
          ### Installation
          
          Download the binary:
          - `hyprlax-x86_64` - hyprlax binary for x86_64 systems (control interface integrated)
          
          ```bash
          # Download binary
          wget https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.version }}/hyprlax-x86_64
          
          # Make executable and install
          chmod +x hyprlax-x86_64
          sudo mv hyprlax-x86_64 /usr/local/bin/hyprlax
          ```
          
          **Note:** The control interface is now integrated. Use `hyprlax ctl <command>` for runtime control.
          
          For ARM64 and other architectures, please build from source.
          
          ### Changes
          
          ${{ steps.notes.outputs.notes }}
          
          ### Checksums
          
          Verify your download with SHA256SUMS file.
          
        files: |
          hyprlax-x86_64
          SHA256SUMS
        draft: false
        prerelease: ${{ contains(steps.version.outputs.version, '-') }}